version: '3.9'

services:
  mongo:
    image: mongo:4.2
    container_name: university-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
